# Docker Compose for Enhanced GPS Tracking System
# Created by Eng. Nawoar Ekkou & Walace Cagnin
#
# This docker-compose.yml provides easy deployment of the GPS tracking system
# with animated forklift movement and colorful trails.

version: '3.8'

services:
  gps-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    image: gps-forklift-tracker:latest
    container_name: gps-tracking-system
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - PYTHONUNBUFFERED=1
    volumes:
      - gps_data:/app/data
      - gps_logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/enhanced_demo.html"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "com.gps.description=Enhanced GPS Forklift Tracking System"
      - "com.gps.version=1.0"
      - "com.gps.location=Göteborg, Sweden"
      - "com.gps.creators=Eng. Nawoar Ekkou & Walace Cagnin"
    networks:
      - gps-network

  # Optional: Add nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: gps-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - gps-tracker
    restart: unless-stopped
    networks:
      - gps-network
    profiles:
      - production

volumes:
  gps_data:
    driver: local
    labels:
      - "com.gps.volume=GPS tracking data"
  gps_logs:
    driver: local
    labels:
      - "com.gps.volume=GPS application logs"

networks:
  gps-network:
    driver: bridge
    labels:
      - "com.gps.network=GPS tracking system network"